import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Header from './components/Header';
import ReduxProvider from './components/ReduxProvider';
import Footer from './components/Footer';
import './styles/globals.css';

const montserratSans = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  style: ['normal'],
  display: 'swap', // Zapewnia natychmiastowe wyświetlenie tekstu z czcionką zastępczą
  fallback: ['sans-serif'],
  preload: false,
});

export const metadata: Metadata = {
  title: 'Next 15 Shop App',
  description: 'Simple shoop generated by Next15 app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // suppress.. is used to prevent warnings related to hydration mismatches between server-rendered and client-rendered content
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserratSans.variable} grid grid-rows-[auto_1fr_auto] min-h-screen w-full font-[family-name:var(--font-montserrat)]`}
      >
        <ReduxProvider>
          <Header />
          <div className="flex flex-col w-full justify-start items-center row-start-2">
            <main className="container flex-col mt-6">{children}</main>
          </div>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
